name: "Docs(문서 작성 및 수정)"
description: README, API 문서 등 문서 관련 작업
title: "[Docs] "
labels: ["documentation"]
body:
  - type: textarea
    id: target
    attributes:
      label: 대상 문서
      description: 어떤 문서를 작성/수정하나요? (README, API 명세 등)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
    validations:
      required: true
